"""Add register date to author

Revision ID: 168d70fbde49
Revises: 599fcd27330e
Create Date: 2021-08-22 07:09:27.149621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168d70fbde49'
down_revision = '599fcd27330e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_model', sa.Column('register_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author_model', 'register_date')
    # ### end Alembic commands ###
