"""Add middlename to author

Revision ID: 599fcd27330e
Revises: 1370315dd29e
Create Date: 2021-08-22 05:56:20.225450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599fcd27330e'
down_revision = '1370315dd29e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_model', sa.Column('middle_name', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author_model', 'middle_name')
    # ### end Alembic commands ###
